### ISSUE TITLE
Convert Pressure Altitude to Geometric Altitude

### ISSUE THREAD

**Issue by mchadwick-iqt** [IQTLabs/SkyScan#12]
ADS-B altitude is reported as pressure altitude, not geometric altitude.  A conversion will have to be done, and may require a barometer at the base station.

Note: this is critical for aiming accuracy for near tracking.  Large slant ranges will  minimize the practical impact of this effect.

**Comment by luke-iqt** [comment]
Current thinking - It looks like the Geo Alt messages are coming in from PiAware... but the adsb-mqtt bridge container may not be processing them. Going to dig some more.

It happens here:
https://github.com/IQTLabs/SkyScan/blob/main/adsb-mqtt/sbs1.py#L79

The messages from PiAware/dump1090 are in a format called sbs-1.

I got my parser from here:
https://github.com/IQTLabs/SkyScan/blob/main/adsb-mqtt/sbs1.py#L79

**Comment by luke-iqt** [comment]
Confirmed - having the H in there caused some a ParseInt call to fail.
https://github.com/IQTLabs/SkyScan/blob/main/adsb-mqtt/sbs1.py#L127

I will see if I can add something more graceful so it will remove any letters from the value first

**Comment by luke-iqt** [comment]
OK - I added in a little re.findall to extract the first set of numbers. seems to work now and is pulling in the Geo Alt

**Comment by luke-iqt** [comment]
JACKPOT! It is doing an amazing job of directly centering the middle on a plane.
