### ISSUE TITLE
aircraft.csv is missing

### ISSUE THREAD

**Issue by robotastic** [IQTLabs/SkyScan#20]
The docs need to add a section describing how to download the .csv file with all of the aircraft info, move it into **/data** and rename it to aircraft.csv.
 
https://opensky-network.org/datasets/metadata/aircraftDatabase.csv

**Comment by mchadwick-iqt** [comment]
Updated documentation to address with commit https://github.com/IQTLabs/SkyScan/commit/68e6bab28fd551b98f83dc1d0ec1224b413ad2cd.  Thanks for noting this @robotastic!
