### ISSUE TITLE
"Nice to have" features for SkyScan 

### ISSUE THREAD

**Issue by robotastic** [IQTLabs/SkyScan#48]
- [ ] A config setting for turning camera movement and capture off. This would be helpful if you want to leave the system running but you don't want the camera moving or taking photos. This could be because it got cloudy out for a little or you are going to perform some quick maintenance on the camera (clean the lens). 
- [ ] Automatically start/stop capture & camera movement based on the time of day... it would be even better if you could have it vary based on sun-up and sun-down. This way you could stop taking photos when it is dusk out and there is not much light left.
- [ ] Take into consideration the cloud layer. If there is a cloud layer at 10k feet, only track planes that are below this altitude. You could also make it simpler and just stop capture when it is cloudy. Conversely, you might be able to determine the visibility range based on whether the ML model can "spot" planes at different altitudes
- [ ] Have some methodology for only capture airplanes based upon different filter for the manufacturer, model, aircraft type or configuration. This could be driven by the different fields in the FAA data... or only capture aircraft that are not in the FAA data.. 
- [ ] It would be great to track the position of the sun and have the camera automatically avoid it. The Camera container could just refuse to move to PTZ locations where the sun is. You have have to do some calculations to correct for Yaw,Pitch,Roll

**Comment by mchadwick-iqt** [comment]
Thanks for the input, @robotastic.  I think some of this will be more easily doable with some of the enhancements we're about to release.  We'll be back in touch on these in a few weeks.
