### ISSUE TITLE
Run in PC

### ISSUE THREAD

**Issue by valeriosouza** [IQTLabs/SkyScan#50]
Is it possible to make this run on a PC with Ubuntu Linux?

**Comment by mchadwick-iqt** [comment]
Good question @valeriosouza - it can run on a PC, we just need to configure the CICD pipeline to build containers for the right processor architecture.

What processor architecture are you using?  We're currently building for linux/arm64 and linux/amd64

**Comment by HitenDroneDefence** [comment]
Will it run with Onvif cameras? such as silent sentinel or red-vision cameras?
