### ISSUE TITLE
Improve secure use of Jupyter Notebook

### ISSUE THREAD

**Issue by Arizbethrojas** [IQTLabs/SkyScan#55]
**Is your feature request related to a problem? Please describe.**
Currently, multiple IP's can listen to the notebook server, which means passwords are vulnerable. 

**Describe the solution you'd like**
Docker secrets enables you to centrally manage sensitive data, such as passwords, and limit the containers that have access to this data. Ultimately, using docker secrets would improve password security.

**Comment by rashley-iqt** [comment]
No longer relevant as of [47f9fd5](https://github.com/IQTLabs/SkyScan/commit/47f9fd5fd176fb66ab0bf0b7a0b8be0818a9f68a)
