### ISSUE TITLE
Change EGI container from privileged flag to device flag

### ISSUE THREAD

**Issue by Arizbethrojas** [IQTLabs/SkyScan#56]
**Is your feature request related to a problem? Please describe.**
Right now, the EGI container, which is the standard interface that works on multiple service providers, runs using the privileged flag on docker. This effectively means that the container has all the capabilities of the host machine, suggesting that a permissions leak is possible.  

**Describe the solution you'd like**
To fix this, we should use a device flag, which does not enable access to the same information that a privileged flag might. At the same time, further testing will be necessary to avoid SkyScan performance impacts.

**Comment by rashley-iqt** [comment]
No longer relevant as of [47f9fd5](https://github.com/IQTLabs/SkyScan/commit/47f9fd5fd176fb66ab0bf0b7a0b8be0818a9f68a)
