### ISSUE TITLE
Testing 1, 2, 3?

### ISSUE THREAD

**Issue by jspeed-meyers** [IQTLabs/SkyScan#6]
@luke-iqt, I am going to have to call the test police. I don't see a single test. For the machine learning journal club this Wednesday, I am doing a presentation on pytest, the popular python testing framework. I am thinking of adding tests to one of the Labs projects that doesn't already have tests. I was considering this project. If there was one file in here that you would appreciate tests for, which one is it? You can also say, "Test police! Get out of here!"

**Comment by luke-iqt** [comment]
The Emoji Police Called! 🚨 There were soooo many missed opportunities in this above Issue.

I think we have a good data flow to dip our toes in the water. We are doing some meter/feet conversions... probably good to make sure that is 💯. 

We could start with this file: https://github.com/IQTLabs/SkyScan/blob/main/tracker/utils.py

Eventually we would want to send MQTT messages and observe the action in different containers...

**Comment by jspeed-meyers** [comment]
😿, don't send the emoji police! I can do better: 🚓, no need to investigate me. Okay, thank you for pointing out this file. I'll make a try at testing those functions via pytest within the next 24 hours. Expect a PR with some unittests.

**Comment by jspeed-meyers** [comment]
Done! PR merged.
