### ISSUE TITLE
Inquiry about specific OS used/supported and Docker version.

### ISSUE THREAD

**Issue by aroop-biswal-vts** [IQTLabs/SkyScan#63]
I was wondering what specific OS is used on the RaspberryPi for this project and what specific versions of Docker Engine and Docker Compose are used.

I am trying to recreate the software setup, but run into some errors with Docker.

When running 'docker-compose build' in this guide: https://github.com/IQTLabs/SkyScan/blob/main/configure-pi.md , the output is "Building 0.0s (0/0)"
 meaning that it didn't recognize any build targets.

Also, in the docker-compose up command, there is an error:
 "no matching manifest for linux/arm/v7 in the manifest list entries"
 suggesting an issue with the OS I am using (Raspbian GNU/Linux 10 (buster)).

Thanks in advance for any feedback.

**Comment by aroop-biswal-vts** [comment]
Is there also any way to run the docker containers on an arm v7 architecture? Currently, the images hosted on Docker Hub are built for amd64 and do not support 32 bit cpus. Thanks.

**Comment by mchadwick-iqt** [comment]
We have only used this system on armv8 processor architectures (Raspberry Pi 4 or PinePhone).  What platform are you trying to run on?  There is nothing that should prevent it from running on an armv7 processor, we just have not tested it to verify. 
 We'll look into adding armv7 images to our base builds on an experimental basis.

In the meantime, if you grab [this commit](https://github.com/IQTLabs/SkyScan/tree/96eb9ad3baaaf86f895803d4d1b67bd34eaa09b9) it will include the previous method for SkyScan deployment, which builds all containers locally.  You should be able to run `docker-compose build` to build all of the containers.

**Comment by aroop-biswal-vts** [comment]
Thanks for the response! We ended up fixing the issue by changing our OS to amd64.
