### ISSUE TITLE
Support for ONVIF ptz cameras?

### ISSUE THREAD

**Issue by samsonpwnz** [IQTLabs/SkyScan#70]
Any possible chance of supporting ONVIF cameras in the future, the robotastic fork supposedly has support for ONVIF but I was not able to get it working, and the mqtt module seems to only run on a arm. I am trying to run this on amd64.

**Comment by mchadwick-iqt** [comment]
Thanks for the question - at this time we are only supporting Axis cameras using the vapix interface.
