### ISSUE TITLE
Feature Request: Drone Detection and Detect by Camera without ADS-B

### ISSUE THREAD

**Issue by PowerPress** [IQTLabs/SkyScan#71]
Would love for the camera to scan around and look for planes or drones it hasn't detected via ADS-B and attempt to identify them from training set.

Additionally could add in WiFi detection for Drone Remote ID.

I would also like to be able to record an additional column when an aircraft is in range via Camera and/OR ADS-B for say 60 seconds or higher and that gets added to database row entry.

Event better if it can alert me one way or another.

**Comment by mchadwick-iqt** [comment]
Thanks for the suggestion!  We're not planning to implement this kind of system in the near future.  We will revisit this at some point.
