### ISSUE TITLE
Calc 3D distance between positions

### ISSUE THREAD

**Issue by luke-iqt** [IQTLabs/SkyScan#8]
Currently, the distance of different planes from the camera is calculated based solely on their 2d positions. The Altitude of the planes should also be taken into consideration.

An additional function should be added, based on [coordinate_distance()](https://github.com/IQTLabs/SkyScan/blob/main/tracker/utils.py#L52) that also takes in altitude and calculates the relative distance in 3 dimensional space between them.

The calls will need to be updated to use this new function:
https://github.com/IQTLabs/SkyScan/blob/main/tracker/flighttracker.py#L156
https://github.com/IQTLabs/SkyScan/blob/main/tracker/flighttracker.py#L352
https://github.com/IQTLabs/SkyScan/blob/main/tracker/flighttracker.py#L374
https://github.com/IQTLabs/SkyScan/blob/main/tracker/flighttracker.py#L413
https://github.com/IQTLabs/SkyScan/blob/main/tracker/flighttracker.py#L430

**Comment by luke-iqt** [comment]
This should have been addressed in commit  https://github.com/IQTLabs/SkyScan/commit/de23e4483c3a3ab20fbf61c274c88b3fa35dbf27 but we saw some issues in the field during testing. Tracking seemed to improve when 2D coordinate distance calculations were used instead. The calculation for this happens here: https://github.com/IQTLabs/SkyScan/blob/main/tracker/utils.py#L51

**Comment by luke-iqt** [comment]
@mchadwick-iqt tested the functionality and confirmed that the calculations were correct. Closing

**Comment by mchadwick-iqt** [comment]
**Test1:**
 - Function computed Slant Range: 35821 meters
   -  Ground Range: 34935 meters
   -  Aircraft Altitude 8031 meters
   -  GPS Altitude 127 meters
 - ManuallyComputed Slant Range: 35817 meters
 - 0.01% error, likely floating point precision loss

**Test2:**
 - Function computed Slant Range: 33127 meters
   -  Ground Range: 31521 meters
   -  Aircraft Altitude 10302 meters
   -  GPS Altitude 127 meters
 - ManuallyComputed Slant Range: 33123 meters
 - 0.01% error, likely floating point precision loss
